paths:
  raw:
    plant_master : "data/raw/PlantMaster.xlsx" 
  intermediate:
    demand : "data/intermediate/PlantDemand.xlsx"
container_size:
    length : 78 #cm
    width : 46 #cm
cell_size: 5
seed_quantity:
    Radish : 8
    Bush Bean : 1
    Stevia : 1
    Garlic : 1
    Zucchini : 1
    Basil : 1
    Chive : 1
solver:
  gap_tolerance : 0.005